version: "3"

services:

  webapp-db:
    image: mariadb:10
    volumes:
      - /var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: webapp
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: webapp

  webapp-api:
    build: api
    depends_on:
      - webapp-db
    ports:
      - 8081:8081
    volumes:
      - ./api:/app
      - /app/vendor
    environment:
      DB_HOST: webapp-db
      DB_DATABASE: webapp
      DB_USERNAME: webapp
      DB_PASSWORD: webapp
      ADMIN_INIT: "true"

  webapp-web:
    build: web
    ports:
      - 8080:8080
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      API_BASE_URL: http://localhost:8081
      WEB_BASE_DIR: /