version: "3"

services:

  webapp-db:
    image: mariadb:10
    volumes:
      - /var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: webapp
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: webapp

  webapp:
    build: .
    depends_on:
      - webapp-db
    ports:
      - 8080:80
    environment:
      DB_HOST: webapp-db
      DB_DATABASE: webapp
      DB_USERNAME: webapp
      DB_PASSWORD: webapp
      ADMIN_INIT: "true"
      WEB_BASE_DIR: /